# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - "2.11.1"
# Branches to test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ross@mongodb.com
    on_success: change
    on_failure: always
jdk:
  - openjdk7
  - oraclejdk7
services:
  - mongodb
