# See http://about.travis-ci.org/docs/user/build-configuration/
language: scala
scala:
  - "2.11.1"
services: mongodb
env:
  - PROJECT=core
  - PROJECT=async
  - PROJECT=rxscala
matrix:
    fast_finish: true
before_script: "mongo --eval 'db.runCommand({setParameter: 1, textSearchEnabled: true})' admin"
script: sbt ++$TRAVIS_SCALA_VERSION $PROJECT/test

# Branches to test
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - ross@mongodb.com
    on_success: change
    on_failure: always
jdk:
  - openjdk7
  - oraclejdk7
